### PR TITLE
Added long/short click support, debug info and minor changes

### PR DESCRIPTION
**Pull request by LuisDiazUgena**
I've added long and short click support. Also, created a debug variable (set to true to show messages on serial monitor). 

I've formatted code to make easier to read to other users.

### CODE REVIEW

**Comment by mrdavidjwatts** [comment]
Thanks, cleaner and adds some extra functionality.

**Comment by LuisDiazUgena** [comment]
Thanks!

My parts will arrive in a few days, so I will be able to test and develop code for the board.

**Comment by mrdavidjwatts** [comment]
On the board you have, there is a small mistake. I have illustrated it here - 
usb-volume

**Comment by LuisDiazUgena** [comment]
Thanks! Will take care when soldering!

**Pull request merged**
